### ISSUE TITLE
New http/get throws on https

### ISSUE THREAD

**Issue by paultopia** [replete-repl/replete-ios#130]
As of latest update adding http: 

```
(require `replete.http)
(replete.http/get "https://gist.githubusercontent.com/paultopia/b36fed87be320bc9d21d28a1692e25ec/raw/74cf569e100e8c26b5107137f5e6c727763ff4ef/evalme.cljs")
```

fails with `Execution error (Error) at (<cljs repl>:1).
Peer certificate cannot be authenticated with given CA certificates
`

I assume this isn't the host's fault since, you know, it's GitHub.  And that url connects with my host's web browser.

I tried passing an options map with `{:insecure true}` as the second argument, and that crashed replete.

**Comment by mfikes** [comment]
Hey @paultopia I can confirm the crash; it is evidently in the native code copied from Planck as it crashes there too planck-repl/planck#894

I can also confirm the CA issue, which is an odd one. (Perhaps it is a manifestation of the derailment when it crashes... let's see if I fix the underlying native issue what happens then.)

**Comment by mfikes** [comment]
Crash issue being handled separately via #131
