### ISSUE TITLE
[newbie issue] can you do console like programming in ios

### ISSUE THREAD

**Issue by kwccoin** [replete-repl/replete-ios#134]
Working on land of lisp to clojure.  As that is a console based book, I wonder whether you can do this here. That is can you ask input instead of I have to use a simulated one.  

Trying 

`
(Require 'replete.core)
(do (print "What's your name? ") 
(flush) 
(replete.core.read-line))`

`
What's your name? 

Execution error (ReferenceError) at (<cljs repl>:1).
Can't find variable: REPLETE_RAW_READ_STDIN
`

Obviously need to handle read input stream but how to get this. 

====

Try 

`
(def y (cljs.reader.read))

Execution error (Error) at (<cljs repl>:1).
Invalid arity: 0

`

Not sure how to proceed.  Just want to get user input.

**Comment by kwccoin** [comment]
Similar to these lines:

`
(defun add-five ()      
(print "please enter a number:")      
(let ((num (read)))          
(print "When I add five I get")          
(print (+ num 5))))

`

**Comment by mfikes** [comment]
Hi @kwccoin, we haven't yet implemented the ability to mimic stdin, which `read-line` would need.

**Comment by kwccoin** [comment]
Ok.  I can still do many of those just no reader.  Good tools and thanks.
