### ISSUE TITLE
Support Dark Mode

### ISSUE THREAD

**Issue by jonathan-arrender-smith** [replete-repl/replete-ios#151]
Entry field for REPL shows text in very very light yellow so not readable at all.  Output text surrounded by heavy black borders. Same on my iPhone and iPad. Continues to be a problem even when I remove the app and re-install from scratch.

**Comment by mfikes** [comment]
Thanks @jonathan-arrender-smith can you perhaps supply a screenshot, out of curiosity.

There was no (intentional) change to rendering code in the latest release, and I'm not able to repro.

It is interesting that you can see it on both your iPhone and iPad... perhaps you have some setting on both that provokes this behavior?

**Comment by jonathan-arrender-smith** [comment]
![4A2CD758-33FB-43A1-9E8B-B09A24D89A31](https://user-images.githubusercontent.com/19222518/71773253-140fd280-2f28-11ea-800a-868eaf17deeb.png)

**Comment by jonathan-arrender-smith** [comment]
Note I typed `(* 2 3)` into the entry field. iPhone looks identical.

**Comment by jonathan-arrender-smith** [comment]
One of the basic IOS settings these days is light or dark theme. Since you did not see the same error, I experimented and found that the problem occurs only when the iPad/iPhone is set to “dark” mode. The application works fine in “light” mode. 

It did work fine in “dark” mode until this last update.

And yes, Replete is important enough to me that I will go ahead and set all of my devices to “light” for now :) Thanks!

**Comment by mfikes** [comment]
![Simulator Screen Shot - iPhone 8 - 2020-01-08 at 20 04 17](https://user-images.githubusercontent.com/1723464/72028861-176dcb80-3252-11ea-822c-7266417d8555.png)

**Comment by mfikes** [comment]
Version 2.3.1 with this fix has been released via the App Store.
